Repository TownOfNext/TownOfNext, pull requests merged in 2023-05, with the labels that each got.

#143 重新整了和平
  Modules/CustomRolesHelper.cs
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Patches/ChatCommandPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/String.csv
  Roles/Crewmate/Divinator.cs
  main.cs
Labels: New Role

#146 Add Dev Tag
  Modules/DevManager.cs
Labels: New Feature

#151 Fix bug comm camouflage
  Modules/Camouflague.cs
  Modules/Utils.cs
  Patches/PlayerContorolPatch.cs
  Patches/SabotageSystemPatch.cs
  Patches/ShipStatusPatch.cs
Labels: Bug
