Repository TownOfNext/TownOfNext, pull requests merged in 2025-02, with the labels that each got.

#206 [Feat] Add chinese version of README
  README.md
  README_zh.md
Labels: Other

#209 小地图新样式
  TONX/Patches/MapBehaviourPatch.cs
  TONX/Patches/MapRealTimeLocationPatch.cs
Labels: New Feature

#210 Update Camouflage and Clean Up Codes
  TONX/Helpers/CustomRolesHelper.cs
  TONX/Modules/Camouflage.cs
  TONX/Modules/CustomRoleSelector.cs
  TONX/Modules/ExtendedPlayerControl.cs
  TONX/Patches/ExilePatch.cs
  TONX/Patches/PlayerControlPatch.cs
  TONX/Resources/Languages/English.yaml
Labels: New Feature

#211 Fix Shapeshift Bugs and Small Changes for Madmate
  TONX/Modules/Camouflage.cs
  TONX/Modules/GameOptionsSender/GameOptionsSender.cs
  TONX/Modules/Utils.cs
  TONX/Patches/MeetingHudPatch.cs
  TONX/Patches/PlayerControlPatch.cs
Labels: Bug

#213 Update README.md
  README.md
  README_zh.md
Labels: Doc Correction

#215 Add Tab Image for Lobby Setting UI and Clean Up Codes
  TONX/Patches/GameOptionsMenuPatch.cs
  TONX/Patches/LobbyViewSettingsPanePatch.cs
Labels: New Feature

#216 优化小地图玩家图标出现逻辑
  TONX/Patches/MapBehaviourPatch.cs
Labels: New Feature

#217 Add PreMeetingPosition and Clean Up Codes
  TONX/Patches/MapBehaviourPatch.cs
  TONX/Resources/ModNews/SChinese/TONX.v3.0.2.txt
  TONX/Roles/Crewmate/Dictator.cs
  TONX/Roles/Crewmate/Doctor.cs
  TONX/Roles/Crewmate/Mayor.cs
  TONX/Roles/Crewmate/TimeManager.cs
  TONX/Roles/Impostor/Bard.cs
  TONX/Roles/Impostor/ShapeMaster.cs
  TONX/Roles/Impostor/TimeThief.cs
  TONX/Roles/Neutral/BloodKnight.cs
  TONX/Roles/Neutral/Collector.cs
  TONX/Roles/Neutral/Hater.cs
  TONX/Roles/Neutral/Innocent.cs
  TONX/Roles/Neutral/Jackal.cs
  TONX/Roles/Neutral/Jester.cs
  TONX/Roles/Neutral/Opportunist.cs
  TONX/Roles/Neutral/Provocateur.cs
  TONX/Roles/Neutral/Sunnyboy.cs
  TONX/Roles/Neutral/Workaholic.cs
Labels: Other

#218 Fix Paranoia
  TONX/Modules/MeetingStartNotify.cs
  TONX/Roles/Crewmate/Paranoia.cs
Labels: Bug
