Repository TownOfNext/TownOfNext, pull requests merged in 2025-10, with the labels that each got.

#255 Android Support
  TONX.sln
  TONX/Helpers/RemoteHelper.cs
  TONX/Modules/BanManager.cs
  TONX/Modules/CustomSounds.cs
  TONX/Modules/ModUpdater.cs
  TONX/Modules/NameTagManager.cs
  TONX/Modules/OptionSaver.cs
  TONX/Modules/OptionSerializer.cs
  TONX/Modules/RPC.cs
  TONX/Modules/RegistryManager.cs
  TONX/Modules/ServerAddManager.cs
  TONX/Modules/SpamManager.cs
  TONX/Modules/TemplateManager.cs
  TONX/Modules/Translator.cs
  TONX/Modules/Utils.cs
  TONX/Patches/AirshipStatus.cs
  TONX/Patches/CredentialsPatch.cs
  TONX/Patches/HudPatch.cs
  TONX/Patches/IntroPatch.cs
  TONX/Patches/MainMenuManagerPatch.cs
  TONX/Patches/OutroPatch.cs
  TONX/Patches/PlayerControlPatch.cs
  TONX/TONX.csproj
  TONX/main.cs
Labels: New Feature

#256 Fix Some Bugs
  TONX.sln
  TONX/Modules/ExtendedPlayerControl.cs
  TONX/Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  TONX/Patches/PlayerControlPatch.cs
  TONX/Roles/Neutral/Jackal.cs
  TONX/TONX.csproj
Labels: Bug

#258 Develop 3.2.0
  TONX/Resources/ModNews/English/TONX.v3.2.0.txt
  TONX/Resources/ModNews/SChinese/TONX.v3.2.0.txt
Labels: Merge2Main
